name: Deploy Terraform Dev IaC
# Deploy infrastructure using Terraform

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}  
  cancel-in-progress: false

env:
  TERRAFORM_DIR: "./terraform"
  TERRAFORM_BACKEND_S3_KEYNAME: "state-file/git-hub/aws-module-terraform/dev/terraform.tfstate"
  TERRAFORM_BACKEND_S3_BUCKET: "807291694811-deployment-bucket-prod"
  TF_VAR_env: '["dev"]'
  TF_VAR_region: "eu-central-1"
  TF_VAR_environment: "dev"
  # TF_VAR_create_access_entries: true
  # VPC
  # TF_VAR_switcher_default_vpc: false
  # TF_VAR_create_vpc_endpoint:  true
  TF_VAR_app_name: "aws-module"
  TF_VAR_vpc_cidr: "10.1.0.0/20"
  # TF_VAR_vpc_azs: '["eu-central-1a", "eu-central-1b", "eu-central-1c"]'
  TF_VAR_vpc_private_subnets: '["10.1.0.0/24", "10.1.1.0/24"]'
  TF_VAR_vpc_public_subnets: '["10.1.2.0/24", "10.1.3.0/24"]'
  TF_VAR_vpc_database_subnets: '["10.1.4.0/24", "10.1.5.0/24"]'
  TF_VAR_vpc_enable_dns_hostnames: true
  TF_VAR_vpc_enable_dns_support: true
  TF_VAR_vpc_enable_nat_gateway: true
  TF_VAR_vpc_single_nat_gateway: true
  TF_VAR_vpc_one_nat_gateway_per_az: false
  # S3
  TF_VAR_bucket_name: "${{ vars.CLOUD_IDENTIFIER }}-dev-bucket"
  # EKS
  TF_VAR_cluster_name: "eks-alpha-dev"
  TF_VAR_node_name: "node-alpha-dev"
  TF_VAR_min_size: 1
  TF_VAR_max_size: 2
  TF_VAR_desired_size: 1
  TF_VAR_disk_size: 20
  TF_VAR_create_node_iam_role: true
  TF_VAR_eks_access_principal_arn: "arn:aws:iam::${{ vars.CLOUD_IDENTIFIER }}:user/admin"

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    # 1. Downloading the code from the repository to the virtual machine GitHub
    - name: Checkout Source Code
      uses: actions/checkout@v6

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.15
  
    - name: Test install app
      run: |
           echo "Testing app installation..."
           terraform --version

    - name: Validate Terraform configuration
      run: terraform -chdir=${TERRAFORM_DIR} fmt -check


  terraform-plan:
    runs-on: ubuntu-latest
    environment: dev
    needs: terraform-check

    steps:
    # 1. Downloading the code from the repository to the virtual machine GitHub
    - name: Checkout Source Code
      uses: actions/checkout@v6

    - name: Authorize to AWS
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.15
  
    - name: Prepare Backend
      run: |
          echo "Testing app installation..."
          terraform --version
          aws --version
          aws sts get-caller-identity
          echo "Using S3 key ${TERRAFORM_BACKEND_S3_KEYNAME} in bucket ${TERRAFORM_BACKEND_S3_BUCKET};"
          cat <<-EOF > ${TERRAFORM_DIR}/backend.tf
            terraform {
              backend "s3" {
                bucket         = "${TERRAFORM_BACKEND_S3_BUCKET}"
                region         = "${AWS_REGION:-eu-central-1}"
                key            = "${TERRAFORM_BACKEND_S3_KEYNAME}"
              }
            }
          EOF
          cat ${TERRAFORM_DIR}/backend.tf

    - name: Initialize Terraform
      run: terraform -chdir=${TERRAFORM_DIR} init

    - name: Terraform Plan deployment
      run: |
          terraform -chdir=${TERRAFORM_DIR} plan -out=tfplan
          terraform -chdir=${TERRAFORM_DIR} show -no-color tfplan > ${TERRAFORM_DIR}/plan.txt

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v7
      with:
        name: terraform-plan
        path: |
          ${{ env.TERRAFORM_DIR }}/tfplan
          ${{ env.TERRAFORM_DIR }}/backend.tf
          ${{ env.TERRAFORM_DIR }}/plan.txt
        retention-days: 1

  terraform-apply:
    runs-on: ubuntu-latest
    environment: dev/review
    needs: terraform-plan
    steps:
    # 1. Downloading the code from the repository to the virtual machine GitHub
    - name: Checkout Source Code
      uses: actions/checkout@v6

    - name: Download Terraform Plan
      uses: actions/download-artifact@v8
      with:
        name: terraform-plan
        path: ${{ env.TERRAFORM_DIR }}

    - name: Authorize to AWS
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.15
  
    - name: Check install app and AWS credentials
      run: |
          echo "Testing app installation..."
          terraform --version
          aws --version
          aws sts get-caller-identity
          echo "Using S3 key ${TERRAFORM_BACKEND_S3_KEYNAME} in bucket ${TERRAFORM_BACKEND_S3_BUCKET};"

    - name: Initialize Terraform
      run: terraform -chdir=${TERRAFORM_DIR} init

    - name: Apply Terraform deployment
      run: terraform -chdir=${TERRAFORM_DIR} apply tfplan
