name: Deploy Terraform IaC
# Deploy infrastructure using Terraform

on:
  push:

permissions:
  contents: read
  id-token: write

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}  
  cancel-in-progress: false

env:
  TERRAFORM_DIR: ./terraform
  TERRAFORM_BACKEND_S3_KEYNAME: state-file/git-hub/dev/aws-module-terraform/terraform.tfstate
  TERRAFORM_BACKEND_S3_BUCKET: 807291694811-deployment-bucket-prod

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    # 1. Downloading the code from the repository to the virtual machine GitHub
    - name: Checkout Source Code
      uses: actions/checkout@v6

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.15
  
    - name: Test install app
      run: |
           echo "Testing app installation..."
           terraform --version

    - name: Validate Terraform configuration
      run: terraform -chdir=${TERRAFORM_DIR} fmt -check


  terraform-plan:
    runs-on: ubuntu-latest
    environment: dev
    needs: terraform-check

    steps:
    # 1. Downloading the code from the repository to the virtual machine GitHub
    - name: Checkout Source Code
      uses: actions/checkout@v6

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.15
  
    - name: Test install app
      run: |
          echo "Testing app installation..."
          terraform --version
          aws --version
          aws sts get-caller-identity
          echo "Using S3 key ${TERRAFORM_BACKEND_S3_KEYNAME} in bucket ${TERRAFORM_BACKEND_S3_BUCKET};"
          cat <<-EOF > ${TERRAFORM_DIR}/backend.tf
            terraform {
              backend "s3" {
                bucket         = "${TERRAFORM_BACKEND_S3_BUCKET}"
                region         = "${AWS_REGION:-eu-central-1}"
                key            = "${TERRAFORM_BACKEND_S3_KEYNAME}"
              }
            }
          EOF
          cat ${TERRAFORM_DIR}/backend.tf

    - name: Initialize Terraform
      run: terraform -chdir=${TERRAFORM_DIR} init

    - name: Plan Terraform deployment
      run: terraform -chdir=${TERRAFORM_DIR} plan -out=tfplan

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v7
      with:
        name: terraform-plan
        path: |
          ${{ env.TERRAFORM_DIR }}/tfplan
          ${{ env.TERRAFORM_DIR }}/backend.tf
        retention-days: 1

  terraform-apply:
    runs-on: ubuntu-latest
    environment: dev/review
    needs: terraform-plan
    steps:
    # 1. Downloading the code from the repository to the virtual machine GitHub
    - name: Checkout Source Code
      uses: actions/checkout@v6

    - name: Download Terraform Plan
      uses: actions/download-artifact@v8
      with:
        name: terraform-plan
        path: ${{ env.TERRAFORM_DIR }}

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.15
  
    - name: Test install app
      run: |
          echo "Testing app installation..."
          terraform --version
          aws --version
          aws sts get-caller-identity
          echo "Using S3 key ${TERRAFORM_BACKEND_S3_KEYNAME} in bucket ${TERRAFORM_BACKEND_S3_BUCKET};"

    - name: Initialize Terraform
      run: terraform -chdir=${TERRAFORM_DIR} init

    - name: Plan Terraform deployment
      run: terraform -chdir=${TERRAFORM_DIR} apply tfplan
