name: Deploy Terraform IaC
# Deploy instance using Terraform

on:
  push:

permissions:
  contents: read

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}  
  cancel-in-progress: true

env:
  TERRAFORM_DIR: ./terraform

jobs:
  terraform-plan-feature-branch:
    runs-on: ubuntu-latest

    steps:
    # 1. Downloading the code from the repository to the virtual machine GitHub
    - name: Checkout Source Code
      uses: actions/checkout@v6
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.15
    - name: Test install app
      run: |
           echo "Testing app installation..."
           terraform --version
           aws --version
           aws sts get-caller-identity

    - name: Validate Terraform configuration
      run: terraform -chdir=${TERRAFORM_DIR} fmt -check




    # - name: Initialize Terraform
    #   run: terraform -chdir=${TERRAFORM_DIR} init

    # - name: Plan Terraform deployment
    #   run: terraform -chdir=${TERRAFORM_DIR} plan

    # - name: Apply Terraform deployment
    #   run: terraform -chdir=${TERRAFORM_DIR} apply -auto-approve
