name: Destroy Terraform IaC
# Destroy EC2 instance using Terraform

on:
  workflow_dispatch:

concurrency:  
  group: ${{ github.workflow }}-${{ github.ref }}  
  cancel-in-progress: false

env:
  TERRAFORM_DIR: ./terraform

jobs:
  terraform-plan-feature-branch:
    runs-on: ubuntu-latest

    steps:
    # 1. Downloading the code from the repository to the virtual machine GitHub
    - name: Checkout Source Code
      uses: actions/checkout@v6

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v6.2.1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: samplerolesession
        aws-region: ${{ vars.AWS_REGION }}      

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.15
    - name: Test install app
      run: |
           echo "Testing app installation..."
           terraform --version
           aws --version
           aws sts get-caller-identity

    - name: Validate Terraform configuration
      run: terraform -chdir=${TERRAFORM_DIR} fmt -check

# jobs:
#   destroy_aws:
#     runs-on: ubuntu-latest

#     steps:
#     # 1. Downloading the code from the repository to the virtual machine GitHub
#     - name: Checkout Source Code
#       uses: actions/checkout@v6
#     - name: Set up Terraform
#       uses: hashicorp/setup-terraform@v2
#       with:
#         terraform_version: 1.15.4
#     - name: Test install app
#       run: |
#            echo "Testing app installation..."
#            terraform --version
#            aws --version
#            aws sts get-caller-identity

#     - name: Initialize Terraform
#       run: terraform -chdir=${TERRAFORM_DIR} init

#     - name: Destroy Terraform deployment
#       run: terraform -chdir=${TERRAFORM_DIR} destroy -auto-approve
